  name: Run Starlark Script

  on:
    push:
      branches:
        - main

  jobs:
    run-starlark:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

         - name: Install Bazel
          run: |
         sudo apt update && sudo apt install -y bazel


        - name: Set up Bazel
          uses: bazel-contrib/setup-bazel@v0.10.0
          with:
            bazel-version: '6.0.0'  # Specify the desired Bazel version

        - name: Verify Bazel workspace
          run: |
            ls -la
            cat MODULE.bazel || echo "No MODULE.bazel found"
            cat WORKSPACE || echo "No WORKSPACE found"

        - name: Run Starlark script
          run: |
            bazel run //hello.star
