name: Run Starlark Script

on:
  push:
    branches:
      - main

jobs:
  run-starlark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Bazel workspace
        run: |
          ls -la
          cat MODULE.bazel || echo "No MODULE.bazel found"
          cat WORKSPACE || echo "No WORKSPACE found"

      - name: Install Bazel
        run: |
          sudo apt update && sudo apt install -y bazel

      - name: Initialize Bazel Workspace
        run: |
          cd $GITHUB_WORKSPACE
          bazel info

      - name: Run Starlark script
        run: |
          bazel run //hello.star
