name: Run Starlark Script

on:
  push:
    branches:
      - main

jobs:
  run-starlark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@v0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}

      - name: Run Starlark script
        run: |
          bazel run //:hello_star
