name: Run Starlark Script

on:
  push:
    branches:
      - main

jobs:
  run-starlark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Starlark script
        run: |
          bazel run //your_starlark_script.star
